language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.18"
    - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - liblog-log4perl-perl
    - libmoose-perl
    - libipc-run-perl
    - libterm-progressbar-perl
    - libgraph-perl
    - libtest-script-run-perl
    - bowtie2
    - ncbi-blast+
    - samtools
    - bedtools
    - r-base
    - ghostscript
    - jellyfish
    - python
before_install:
    - export PATH=$TRAVIS_BUILD_DIR:/tmp/SPAdes-3.10.1-Linux/:$PATH
install:
    - perl -v
    - cpanm Term::ProgressBar Graph Log::Log4perl Moose File::Which IPC::Run Test::Script::Run
    - wget -O /tmp/SPAdes-3.10.1-Linux.tar.gz http://cab.spbu.ru/files/release3.10.1/SPAdes-3.10.1-Linux.tar.gz && cd /tmp/ && tar -xzf SPAdes-3.10.1-Linux.tar.gz
script:
    - cd $TRAVIS_BUILD_DIR
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrv test/chloroExtractor-testsuite/cmd_based/*.t
    - cover
after_success:
    - cover -report coveralls
