language: perl
perl:
  - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - liblog-log4perl-perl
    - libmoose-perl
    - libipc-run-perl
    - libterm-progressbar-perl
    - libgraph-perl
    - bowtie2
    - ncbi-blast+
    - samtools
    - bedtools
    - r-base
    - ghostscript
    - jellyfish
    - python
before_install:
    - git clone https://github.com/sstephenson/bats.git $HOME/bats
    - export PATH=$TRAVIS_BUILD_DIR:/tmp/SPAdes-3.10.1-Linux/:$HOME/bats/bin:$PATH
install:
    - perl -v
    - cpanm Term::ProgressBar Graph Log::Log4perl Moose File::Which IPC::Run
    - wget -O /tmp/SPAdes-3.10.1-Linux.tar.gz http://cab.spbu.ru/files/release3.10.1/SPAdes-3.10.1-Linux.tar.gz && cd /tmp/ && tar -xzf SPAdes-3.10.1-Linux.tar.gz
script:
    - cd $TRAVIS_BUILD_DIR
    - bats --tap test/chloroExtractor-testsuite/cmd_based/*.bats
