language: perl
perl:
  - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - liblog-log4perl-perl
    - libmoose-perl
    - libipc-run-perl
    - libterm-progressbar-perl
    - libgraph-perl
    - bowtie2
    - ncbi-blast+
    - samtools
    - bedtools
    - r-base
    - ghostscript
    - jellyfish
    - python
install:
    - perl -v
    - cpanm .
script: 
    - perl Makefile.PL
    - make 
    - make test
