language: perl
perl:
  - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - liblog-log4perl-perl
    - libmoose-perl
install:
    - perl -v
    - cpanm .
script: 
    - perl Makefile.PL
    - make 
- make test
